version: "3.9"

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - "./final:/final"
      - "./uploaded_chunks:/uploaded_chunks"
      - "./cinaftv-movies:/cinaftv-movies"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
